version: "3.7"

services:
  mysql:
    restart: unless-stopped

  pma:
    restart: unless-stopped

  proxy:
    restart: unless-stopped
    environment:
      - ACME_AGREE=true
    ports:
      - 80:80
      - 443:443

  nextjs-nexus:
    restart: unless-stopped
    environment:
      ENV_MODE: production
    build:
      args:
        - ENV_MODE=production
    command: bash -c "yarn start"

  rtcmultyconnection:
    restart: unless-stopped

  coturn:
    restart: unless-stopped

  tileserver:
    restart: unless-stopped

  tolgee:
    restart: unless-stopped

  libretranslate:
    restart: unless-stopped
